### ISSUE TITLE
Filters for tasks

### ISSUE THREAD

**Issue by miramir** [deecay/redmine_pivot_table#12]
For example: I need show table for estimated time by people for task closed in this month or week

**Comment by deecay** [comment]
Hi miramir,

There is no straighforward way of doing that. I will however, share with you one instruction and one proposition. Please let me know what you think.

A. Instruction
The closest result can be achieved by the following steps.
1. Check "include closed"
2. Click the filter triangle next to "Closed" attibute to show filter dialog.
3. Click on "Select None".
4. Type in filter value such as "2016/01" to narrow down.
5. Click "Select All", then "OK".

The pivot should now show the number of issues closed within a designated range.

B. Proposition for improvement
What I can do is add functionality to automatically add attributes "Closed (y)", "Closed (m)", "Closed (w)", and "Closed (d)".
I assume this will allow you to filter quicker. You won't be able to filter like "last 30 days", but you can jump to "January of 2015" or "Week 4 of 2016". If you want to see a weekly summary, you just neet do drag "Closed (y)" and "Closed (w)" to the horizontal attributes.

I did not implement this because there are many date attributes, and expanding year, week, and other attributes to all date field could clutter the available attribute panel.


So, i guess the choice is 
1. Add additional date attributes to all date fields.
2. Add additional date attributes to "Closed".
3. Do nothing.

Hope this helps.

**Comment by deecay** [comment]
Oh, and for the estimated time by people, drag "assigned to" to vertical attribute, select "Sum" as an aggregator, and "Estimated time" as aggregated field.
