### ISSUE TITLE
Issue's subject is not deduplicated

### ISSUE THREAD

**Issue by silversmarty** [deecay/redmine_pivot_table#21]
Hi !

i've notived that even if I have two issues with the same subject, they will appear in two different lines in the pivot table : 
![image](https://cloud.githubusercontent.com/assets/17980711/15667901/ee214d6c-2718-11e6-9ab4-f5259d306241.png)

Or I need to have them on one line only : it's the main purpose for a pivot table ;-)
Is there someone else having this problem ? How can this be fixed ?

Thanks !

**Comment by deecay** [comment]
Hi,

That's because thay have different ticket IDs. To make the title clickable, they have unique jump-to address for each issue. Pivottable recognizes these two entries as different entries.

I will plan on removing an HTML link from title, to avoid this unintuitive behaviour. ID field can still be used when link is necessary.

**Comment by silversmarty** [comment]
it would be awesome, thanks !!

**Comment by deecay** [comment]
HEAD version should solve this problem.
